"use strict";
/* Generated file to emulate the ts namespace. */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !Object.prototype.hasOwnProperty.call(exports, p)) __createBinding(exports, m, p);
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.performance = exports.moduleSpecifiers = void 0;
__exportStar(require("../corePublic"), exports);
__exportStar(require("../core"), exports);
__exportStar(require("../debug"), exports);
__exportStar(require("../semver"), exports);
__exportStar(require("../performanceCore"), exports);
__exportStar(require("../perfLogger"), exports);
__exportStar(require("../tracing"), exports);
__exportStar(require("../types"), exports);
__exportStar(require("../sys"), exports);
__exportStar(require("../path"), exports);
__exportStar(require("../diagnosticInformationMap.generated"), exports);
__exportStar(require("../scanner"), exports);
__exportStar(require("../utilitiesPublic"), exports);
__exportStar(require("../utilities"), exports);
__exportStar(require("../factory/baseNodeFactory"), exports);
__exportStar(require("../factory/parenthesizerRules"), exports);
__exportStar(require("../factory/nodeConverters"), exports);
__exportStar(require("../factory/nodeFactory"), exports);
__exportStar(require("../factory/emitNode"), exports);
__exportStar(require("../factory/emitHelpers"), exports);
__exportStar(require("../factory/nodeTests"), exports);
__exportStar(require("../factory/utilities"), exports);
__exportStar(require("../factory/utilitiesPublic"), exports);
__exportStar(require("../parser"), exports);
__exportStar(require("../commandLineParser"), exports);
__exportStar(require("../moduleNameResolver"), exports);
__exportStar(require("../binder"), exports);
__exportStar(require("../symbolWalker"), exports);
__exportStar(require("../checker"), exports);
__exportStar(require("../visitorPublic"), exports);
__exportStar(require("../sourcemap"), exports);
__exportStar(require("../transformers/utilities"), exports);
__exportStar(require("../transformers/destructuring"), exports);
__exportStar(require("../transformers/taggedTemplate"), exports);
__exportStar(require("../transformers/ts"), exports);
__exportStar(require("../transformers/classFields"), exports);
__exportStar(require("../transformers/typeSerializer"), exports);
__exportStar(require("../transformers/legacyDecorators"), exports);
__exportStar(require("../transformers/esDecorators"), exports);
__exportStar(require("../transformers/es2017"), exports);
__exportStar(require("../transformers/es2018"), exports);
__exportStar(require("../transformers/es2019"), exports);
__exportStar(require("../transformers/es2020"), exports);
__exportStar(require("../transformers/es2021"), exports);
__exportStar(require("../transformers/esnext"), exports);
__exportStar(require("../transformers/jsx"), exports);
__exportStar(require("../transformers/es2016"), exports);
__exportStar(require("../transformers/es2015"), exports);
__exportStar(require("../transformers/es5"), exports);
__exportStar(require("../transformers/generators"), exports);
__exportStar(require("../transformers/module/module"), exports);
__exportStar(require("../transformers/module/system"), exports);
__exportStar(require("../transformers/module/esnextAnd2015"), exports);
__exportStar(require("../transformers/module/node"), exports);
__exportStar(require("../transformers/declarations/diagnostics"), exports);
__exportStar(require("../transformers/declarations"), exports);
__exportStar(require("../transformer"), exports);
__exportStar(require("../emitter"), exports);
__exportStar(require("../watchUtilities"), exports);
__exportStar(require("../program"), exports);
__exportStar(require("../builderStatePublic"), exports);
__exportStar(require("../builderState"), exports);
__exportStar(require("../builder"), exports);
__exportStar(require("../builderPublic"), exports);
__exportStar(require("../resolutionCache"), exports);
__exportStar(require("../watch"), exports);
__exportStar(require("../watchPublic"), exports);
__exportStar(require("../tsbuild"), exports);
__exportStar(require("../tsbuildPublic"), exports);
var moduleSpecifiers = require("./ts.moduleSpecifiers");
exports.moduleSpecifiers = moduleSpecifiers;
var performance = require("./ts.performance");
exports.performance = performance;
